/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kspammer;

import ch.virt.kahoot.api.Kahoot;


public class App {
    static String gameId = "";
    static String name = "cool";

    public static void main(String[] args) {
        System.out.println("hi");
        Kahoot.joinGame(name, gameId, new KahootGameProcessor());
    }
}
